
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZYYGameKit.Localization.Generate
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["ChineseSimplified"].IsString) { throw new SerializationException(); }  ChineseSimplified = _buf["ChineseSimplified"]; }
        { if(!_buf["English"].IsString) { throw new SerializationException(); }  English = _buf["English"]; }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new Localization.Generate.Language(_buf);
    }

    public readonly string Key;
    public readonly string ChineseSimplified;
    public readonly string English;
   
    public const int __ID__ = -1038661700;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "ChineseSimplified:" + ChineseSimplified + ","
        + "English:" + English + ","
        + "}";
    }
}

}
