
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ZYYGameKit
{
public partial class Tables
{
    public Localization.Generate.TbLanguage TbLanguage {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbLanguage = new Localization.Generate.TbLanguage(loader("localization_generate_tblanguage"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbLanguage.ResolveRef(this);
    }
}

}
